### PR TITLE
report_dispatcher fix

### PR DESCRIPTION
**Pull request by almartin82**
report dispatcher only worked if you passed the organizational cuts in alphabetical order!  if you tried to do something else, you were screwed! :see_no_evil: :see_no_evil: :see_no_evil: 

also my hacky implementation of 'what permutations are there in this data set' can be replaced with one call to `unique()` on the data frame.  WHO KNEW!?  not I.

### CODE REVIEW

**Comment by almartin82** [comment]
@chrishaid best -48 lines of code I've ever written.

**Comment by almartin82** [comment]
I merged this patch under the same principle as before - hotfixes/patches on code in production can be immediately merged; new features need a review by a contributor.

**Comment by chrishaid** [comment]
Im good with that principal for hot patches. 

Good news about unique.  

You know about  grid.expand for building up every permutation of multiplied variables into a data.frame, right? 

—

**Comment by almartin82** [comment]
I tried that but it doesn't do only unique expansions. Unique does only the
unique permutations

(mobile)

**Pull request merged**
