### PR TITLE
changes to facilitate workflows from a data warehouse

### PR DESCRIPTION
**Pull request by almartin82**
Nothing too suprising, but @chrishaid want your opinion on some new logic in [mapvizier_object](https://github.com/almartin82/mapvizieR/blob/a7516f63a9a18c139a2bc70867181bbe7602addc/R/mapvizieR_object.R#L22)

until now, I've been working on example data, with the presumption that it's basically 6/half dozen with data from our data warehouse.  turns out that's not the case.  new design pattern here is basically:
- check if the cdf object conforms to mapvizieR expectations
- if yes, great, move forward to the growth calculations; if no, call the cgp prep and cgp process functions.

as a general design pattern, are you OK with this direction?  the advantage, in my mind, is clarity -  you call the same constructor function, and mapvizieR tries to figure out what to do based on the state of your data.

but alternatively we could rename `mapvizieR` and create two distinct functions - say, `mapvizieR_raw` and `mapvizieR_datamart`, or something, for folks who are doing some of the matching/pre-processing in a database.

tests _should_ pass - passing locally.

### CODE REVIEW

**Comment by almartin82** [comment]
whoops, forgot to check the vignette.  fixing...

**Comment by almartin82** [comment]
tests were passing, but build/ CMD check didn't - fixed the vignettes, should be in business now

**Comment by chrishaid** [comment]
Cool. I'll merge when ti passess.

**Comment by almartin82** [comment]
ok, I think we're set now.  @chrishaid I think this is ready to be merged, provided that travis agrees...

**Comment by chrishaid** [comment]
Merged!

**Comment by almartin82** [comment]
nice.  
tests are the saving grace.  we are well past the number of lines of code where I can't keep track of things in my head...

**Pull request merged**
