### PR TITLE
groups

### PR DESCRIPTION
**Pull request by almartin82**
so I closed an older PR on this branch (#297), but re-opening, because there's a lot of important code here that needs to get back to master.

to solve #294, we need to implement #304 - @chrishaid let's keep this PR open and try to get this done by the end of the week!

### CODE REVIEW

**Comment by chrishaid** [comment]
Do you want me to merge this now, or to wait?

**Comment by almartin82** [comment]
wait, it's not ready yet :/

**Comment by almartin82** [comment]
@chrishaid this is getting crazy - this branch is SO far out ahead.  I will try to prioritize the dplyr wrappers so that we can bring this baby back to master.  would love any help you can provide...

**Review by chrishaid — APPROVED** [review]
Looks good.

**Comment by almartin82** [comment]
@chrishaid the crucial change is [here](https://github.com/almartin82/mapvizieR/blob/3343a0b5747be323712c30accccc10785f53c38b/R/mapvizier_summary.R#L92)

**Comment by chrishaid** [comment]
This pull request isnt mergable.  It has conflicts (see above). Plus tests are failing.

**Comment by almartin82** [comment]
@chrishaid this is passing [wercker](https://app.wercker.com/almartin/mapvizieR/runs/build/5899ed4f219b2701006be51a)

**Pull request merged**
