### PR TITLE
haid_plot fixes for 'empty' ending quartile; elephants patch

### PR DESCRIPTION
**Pull request by almartin82**
two fixes in this pull request; one makes sure that `haid_plot` can correctly handle data where the there are no students in one of the quartile bins at the _start_ of the window, but who do enter by the end.  frankly that code is a mess and is a good candidate for refactoring.  but tests should pass now.

another is a patch on elephants that I described on #87 (closed pull req) - basically the assumption that the maximum value of a `geom_density` curve would be one point is incorrect, because sometimes (due to rounding) there are 2 x values for the associated maximum y value.  a :100: for throwing random inputs at our plots, though. 

@chrishaid for review

### CODE REVIEW

**Comment by chrishaid** [comment]
This looks good.  I'll merge when it passes Travis CI.  If we were only on wrecker it would have passed by now.

**Comment by almartin82** [comment]
Yeah that's on my to-dos today :)

(mobile)

**Comment by chrishaid** [comment]
Failed :scream_cat:

**Comment by almartin82** [comment]
channeling my inner [sasha](https://www.youtube.com/watch?v=hY14Er6JX2s):
[Imgur](http://i.imgur.com/4KVXM21.png)

**Comment by almartin82** [comment]
any ideas what that [error](https://travis-ci.org/almartin82/mapvizieR/builds/61307059#L1657) is about?  segmentation fault?

**Comment by chrishaid** [comment]
Segfaults are errors raised by the hardware (like the chip set) and usually indicate a memory access violation. From my experience they are caused by super low level stuff.

**Comment by almartin82** [comment]
trying again.  added another test.  hopefully that segfault error was ephemeral?  passed tests locally on my machine.

**Comment by almartin82** [comment]
go figure - everything passes (finally).

**Pull request merged**
