### PR TITLE
Added median columns to summary method.

### PR DESCRIPTION
**Pull request by chrishaid**
@almartin82 for you review

### CODE REVIEW

**Comment by almartin82** [comment]
@chrishaid back at you here - I added CGP to the summary (and bumped the version number).  give it a gander...

**Comment by almartin82** [comment]
nb, if you need to get one of these locally while you are waiting for a pull request to go through, 

```
install_github("almartin82/mapvizieR", ref="median_summaries")
library(mapvizieR)
```

or

```
devtools::load_all(pkg = "/Users/almartin/Repositories/mapvizieR")

```

**Comment by almartin82** [comment]
hmm, interesting - summary cgp calcs don't agree with other cgp calcs -- because the summary method doesn't filter by complete obsv...

**Comment by almartin82** [comment]
@chrishaid can we merge this one too?

**Comment by chrishaid** [comment]
@almartin82 merged.

**Pull request merged**
