### PR TITLE
new grouping method

### LINKED ISSUE #294: cdf summary and growth_df summary should respect incoming groups
per a great suggestion by @chrishaid, instead of setting the groups in the summary method, the mapvizieR object should set the groups, and the summary method should use the incoming groups, whatever those are.

### PR DESCRIPTION
**Pull request by almartin82**
closes #294

### CODE REVIEW

**Comment by almartin82** [comment]
@chrishaid this [comment](https://github.com/hadley/dplyr/issues/1429#issuecomment-152344873) is sad for us

dplyr `group_by`s don't preserve the class of the object...

**Comment by almartin82** [comment]
@chrishaid these wercker builds claim to be passing, but in reality CMD check is failing...

from the details of the wercker build above:

```
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  Loading required package: gridExtra
  Loading required package: magrittr

  Attaching package: 'magrittr'

  The following objects are masked from 'package:testthat':

      equals, is_less_than, not

  Error: 'summary.mapvizieR_cdf' is not an exported object from 'namespace:mapvizieR'
  testthat results ================================================================
  OK: 181 SKIPPED: 0 FAILED: 0
  Execution halted
```

that's definitely not a pass...

**Comment by almartin82** [comment]
@chrishaid been thinking about this for a minute.  I see hadley's point - dplyr is a data pipeline package.  if you're using it, you're changing the object.  in my head, the default behavior would be to preserve the class of the object after transformation, but maybe that's not true for everyone.

trying to think about how to write custom mapvizieR method dispatch per hadley's suggestion.  is it just:
- capture the classes on the way in 
- pass the arguments to the dplyr function
- restore the classes on the way out?

that wouldn't be very hard...

**Comment by almartin82** [comment]
this is not ready for prime time yet.

**Comment by chrishaid** [comment]
This is the saddest aborted pull request on mapvizieR ever.

I agree.  We should just write 'dplyr verb' methods that dispatch on out classes.  
1. Take object and record classes
2. Apply dplyr verb to data
3. Add back saved classes.

**Pull request closed without merging**
