### PR TITLE
quealy subgroups does cgp grade level per subgroup. closes #157

### LINKED ISSUE #157: quealy subgroups should calculate approximate grade per group

### PR DESCRIPTION
**Pull request by almartin82**
@chrishaid pretty simple patch here - if we are running quealy_subgroups across, say, a whole school's worth of data, and grade provided as a subgroup, we should do the grade level per subgroup.    anything else is confusing / borderline dangerous.

also the quealy tests were commented out - probably when we were in namespace or segfault hell?

### CODE REVIEW

**Comment by almartin82** [comment]
@chrishaid this is a somewhat more substantial change here - we want to allow for the function (if desired) to guess the best start term/growth window, given the data.  so if you specify start_fws, (length ==1) it will do what you tell it to do; if you pass two terms (eg `c('Spring', 'Fall')`) it will use the first one if it can, falling back to the second if it can't.  

one note here is that this introduces breaking changes to `quealy_subgroups` -- instead of passing `start_academic_year` we are passing `start_year_offset` (which then gets handed down to `auto_windows`.  not a _huge_ change but you'll want to go look at anything you have in production.

**Comment by almartin82** [comment]
writing that out reminded me: oh yeah, go update the vignette.

**Comment by almartin82** [comment]
nm, we don't have a vignette for that (we should!).  i will fix that broken test on `auto_growth_window` though.

**Comment by almartin82** [comment]
@chrishaid this is good to go

**Comment by chrishaid** [comment]
Merged!  I think there's a good chance we'll get our builds building again once the auto_growth_window patched up

**Comment by almartin82** [comment]
yeah that was dumb.  sorry about that

**Pull request merged**
