### PR TITLE
a function that throws random student subsets against a plot, for testing

### PR DESCRIPTION
**Pull request by almartin82**
also did a little cleanup on `galloping_elephants` to get the `first_and_spring_only` logic to work correctly.  @chrishaid can you review and merge?  

this will hopefully catch weird edge cases.  we can throw random subsets of students against a plot hundreds of times and see if ggplot errors on any of the subsets.

### CODE REVIEW

**Comment by chrishaid** [comment]
Closing this request.

The fuzzy_test is awesome but needs one additional feature: it should return the list of student IDs and and the call (Function name and parameters) of any failures. These should be bundled up in a list. 

Also, why hasn't this really great function been written?  Probably an opportunity to abstract this test and add to devtools.

**Comment by almartin82** [comment]
great points! 

how do you feel about this output for fuzz plot when it fails?

```
results <- fuzz_test_plot('error_ridden_plot', n=3)
Error in exists(name, envir = env, mode = mode) : 
  argument "env" is missing, with no default
Error in exists(name, envir = env, mode = mode) : 
  argument "env" is missing, with no default
Error in exists(name, envir = env, mode = mode) : 
  argument "env" is missing, with no default
fuzz testing error_ridden_plot failed!
outputting studentid vectors that caused error_ridden_plot to fail:
c("SF07001863", "SF07001792", "SF06000359", "F08000216", "SF06000630",
"SF06000762", "SF07002341", "SF06000070", "SF07001603", "SF07002084",
"SF07002351", "F08000136", "SF07002302", "F08000160", "SF07001626", ...)

c("F08000059", "F08000010", "F08000123", "F08000245", "SF06000797",
"SF06000147", "F08000284", "SF06000509", "SF07002425", "F08000032",
"SF07002044", "F08000246", "F08000011", "SF07002134", "F08000316", ...)

c("F08000030", "SF07001677", "SF07001743", "SF07002084", "F08000045",
"SF07002050", "SF07002303", "SF06000382", "SF07002149", "SF07002220",
"SF07002406", "SF06001032", "SF06000730", "SF07002183", "SF07002246", ...)
```

(I truncated the studentid vectors for clarity).

it always returns a list of pass/fails, but will output the bad studentids to help reproduce the test failure.  @chrishaid how does that work?

**Comment by chrishaid** [comment]
Yes!

**Comment by chrishaid** [comment]
Should I reopen this pull request and merge?

c

**Comment by almartin82** [comment]
I'll have a new commit shortly (waiting on CMD check)

(mobile)

**Pull request closed without merging**
