### PR TITLE
add haid_plot to mapvizier

### LINKED ISSUE #74: move haid_plot over to mapvizieR

### PR DESCRIPTION
**Pull request by almartin82**
ports haid_plot over to mapvizier!  simplified some of the code from mapvisuals.  note #80 - the colors for student names are now all aligned to growth status.  @chrishaid for review.  closes #74.

### CODE REVIEW

**Comment by chrishaid** [comment]
Man, even losing 3% covererage and we aer still at 96.6% . Nice.

**Comment by almartin82** [comment]
so a big part of why we lost coverage was the code on `haid_plot` that handles the situations where there are missing quartiles in the start or end of the data file.  I'll try to find a test case for that.

**Comment by almartin82** [comment]
found a test case.  let's just say: good thing we're testing ALL the code, not just some :see_no_evil:

**Comment by chrishaid** [comment]
Nice!

—

**Pull request merged**
