### PR TITLE
fall goal report and student plots

### PR DESCRIPTION
**Pull request by almartin82**
@chrishaid this is not ready to go (yet) but I wanted to open a thread so that you could start reviewing this merge (there's a lot of new code here) and maybe suggest high-priority documentation and tests?

### CODE REVIEW

**Comment by almartin82** [comment]
getting closer!  more tests and documentation to write.

**Comment by almartin82** [comment]
@chrishaid I think this is ready for your review, now -- all functions have documentation and I think everything has basic test coverage (although some of the tests are pretty minimal).  let's see if this passes tests...

**Comment by almartin82** [comment]
hmm, the logs say

```
  1. Error: npr templates generate correctly 
  2. Error: npr template generates correctly with old and new norms 
  3. Error: npr templates with various options 
  4. Error: cohort longitudinal plot with sample students 
```

but those just ran clean on my local machine.  headed to the grocery store, but that is next up for investigation.

**Comment by chrishaid** [comment]
Perhaps a package version problem?

**Comment by almartin82** [comment]
codecov works again :+1:

**Comment by almartin82** [comment]
@chrishaid was just talking about [this](https://github.com/almartin82/mapvizieR/blob/82a3394f60197a369b150a7d541b72f76331f242/R/mapvizier_summary.R#L36) logic with @kimjam -- it solves issue #188 (a CMD-check problem), and basically gives the same behavior - we can specify `digits` to `mapvizier.summary`, but if nothing is specified, it defaults to 2.  it's not a one liner, so it's not capital E elegant, but I think I can still sleep at night?

nb, I tested it without the else, and it throws 

```
ex2 <- summary(mapviz, digits = 3)
 Error: object 'digits' not found 
```

the internal environment of that function doesn't seem to look in the namespace of the `...` -- you actually have to say HEY LOOK IN THE DOTS FOR THIS VALUE relatively explicitly.

**Comment by almartin82** [comment]
files changed: 202!

good news is that the upgraded version of roxygen doesn't print the version number at the top anymore (meaning way fewer spurious changes, like this one).  @chrishaid you probably need to force RStudio to upgrade

**Pull request merged**
