### PR TITLE
better date handling

### PR DESCRIPTION
**Pull request by almartin82**
@chrishaid this is a simple pull req that changes some workflow logic in cdf prep -- if travis passes can you merge?
trying to get our (TEAM) data into the mv object and need some better date parsing logic

### CODE REVIEW

**Comment by chrishaid** [comment]
Looks good.  I'll merge once Travis says it is ok.

c

**Comment by almartin82** [comment]
Is there a more elegant way to dplyr chain those measurement / date cleanup
functions? trying to avoid `rowwise ()` as it is pretty slow

(mobile)

**Comment by chrishaid** [comment]
Can you point me to file line number.  I see the `munge_start_date` but I don't see the `rowwise()` bit.

**Comment by almartin82** [comment]
I killed the rowwise before committing - but it was wildly slow when I was
testing it

(mobile)

**Pull request merged**
